name: 04 - using-actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Use an action from the GitHub Marketplace
        uses: actions/setup-node@v5
        with:
          node-version: '22.x'
      - name: listing files
        run: ls
        working-directory: 04-using-actions/react-app

      - name: Install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
  

      - name: Run tests
        run: npm  test
        working-directory: 04-using-actions/react-app
  
