name: 04 - using-actions
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use an action from the GitHub Marketplace
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        working-directory: 04-using-actions/react-app
        run: npm ci
        

      - name: Run tests
        run: npm run test
  
